version: "3.1"
services:
  docker-mongo:
    image: "mongo"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME:root"
      - "MONGO_INITDB_ROOT_PASSWORD:example"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - MONGOUSER=mongo
      - MONGOPASSWORD=mongo_password
      - MONGOPORT=27017
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
      - MONGOUSER=mongo
      - MONGOPASSWORD=mongo_password
      - MONGOPORT=27017
