version: "3.7"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: docker-mongo
    links:
      - mongo-db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    links:
      - api:api
      - client:client
    ports:
      - "3050:80"
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
